{"errorMessage":"Lambda process returned error status code: 1. Result: . Output:\nnode:internal/errors:490\n    ErrorCaptureStackTrace(err);\n    ^\n\nTypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined\n    at new NodeError (node:internal/errors:399:5)\n    at Function.from (node:buffer:334:9)\n    at exports.handler (/tmp/function.zipfile.ddceba4c/server/messages/sendImage.js:10:30)\n    at [eval]:1:84\n    at Script.runInThisContext (node:vm:129:12)\n    at Object.runInThisContext (node:vm:307:38)\n    at node:internal/process/execution:79:19\n    at [eval]-wrapper:6:22\n    at evalScript (node:internal/process/execution:78:60)\n    at node:internal/main/eval_string:28:3 {\n  code: 'ERR_INVALID_ARG_TYPE'\n}\n\nNode.js v18.14.0","errorType":"InvocationException","stackTrace":["  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 1423, in do_execute\n    execute_result = lambda_function_callable(inv_context.event, context)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_api.py\", line 807, in execute\n    result = lambda_executors.EXECUTOR_LOCAL.execute_javascript_lambda(\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 1585, in execute_javascript_lambda\n    result = self._execute_in_custom_runtime(cmd, lambda_function=lambda_function)\n","  File \"/opt/code/localstack/localstack/services/awslambda/lambda_executors.py\", line 1366, in _execute_in_custom_runtime\n    raise InvocationException(\n"]}
